spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:h2:~/data/sms.db;NON_KEYWORDS=USER
    username: sa
    password:

  thymeleaf:
    prefix: classpath:/templates/
    sufix: .html

jwt:
  secret-key: sports-matching-service-secret-key
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420

mail:
  address:
    admin: admin@gmail.com

social:
  kakao:
    params:
      clientId: 22b97acad5abe9c20aa6d5b4740fccb4
      clientSecret: 7Qz7wEYSkZDetbVFlny97RJ3oXvOgCNj
    path:
      redirectUri: http://localhost:8080/users/oauth/tokens/kakao
      userInfoUrl : https://kapi.kakao.com/v2/user/me
      tokenUrl: https://kauth.kakao.com/oauth/token

