spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:h2:~/data/sms.db;NON_KEYWORDS=USER
    username: sa
    password:
